### ISSUE TITLE
Funcionalidades Basicas

### ISSUE THREAD

**Issue by InahoAZ** [InahoAZ/wallexcel#4]
- [ ] #1 Gestion de Cuentas de Dinero
- [ ] #2 Gestion de Categorías
- [ ] #3 Registro de Movimientos
